# Generated by Django 4.0.3 on 2022-07-31 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movie_data',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('released_year', models.DateField()),
                ('ratings', models.FloatField()),
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('genres', models.CharField(max_length=10)),
            ],
        ),
    ]
