# Generated by Django 4.0.3 on 2022-07-31 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mDb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_data',
            name='released_year',
            field=models.IntegerField(),
        ),
    ]
