# Generated by Django 4.0.3 on 2022-07-31 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mDb', '0002_alter_movie_data_released_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_data',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
