# Generated by Django 4.0.3 on 2022-07-31 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mDb', '0003_alter_movie_data_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_data',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
